[package]
name = "dvm-test-kit"
version = "0.1.0"
authors = [
    "Alex Koz. <alexanderkozlovskii@wings.ai>",
    "Dm. Yakushev <dmitryyakushev@wings.ai>",
    "Maxim Kurnikov <maximkurnikov@wings.ai>"
    ]
edition = "2018"


[dependencies]
dvm = { path = ".." }
dvm-api = { git = "https://github.com/dfinance/dvm-proto.git", branch = "master" }
libra = { path = "../libra", package = "dvm-libra-deps" }
data_source = { path = "../data-source", package = "dvm-data-source" }
lang = { path = "../lang", package = "dvm-lang" }
anyhow = "=1.0.27"
tokio = { version = "=0.2", features = [ "macros", "rt-core", "rt-threaded", "blocking", "full" ] }
futures = { version = "=0.3.4", features = ["async-await"] }
serde = "=1.0.104"
serde_json = "=1.0.48"
serde_derive = "=1.0.104"
hex = "=0.4.2"
